// Mock Library Content Data
export const mockLibraryContent = [
  {
    id: '1',
    title: 'Introduction to Mindfulness',
    description: 'Learn the basics of mindfulness meditation and how to incorporate it into your daily routine for better mental health.',
    type: 'article' as const,
    category: 'mindfulness' as const,
    readTime: 5,
    thumbnail: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800',
    url: 'https://example.com/mindfulness',
    author: 'Dr. Sarah Johnson',
    publishedAt: '2024-11-20T00:00:00Z',
    isBookmarked: false,
    viewCount: 1243,
    tags: ['meditation', 'beginner', 'wellness'],
  },
  {
    id: '2',
    title: 'Managing Stress in Modern Life',
    description: 'Practical strategies and techniques to reduce stress and anxiety in your everyday life.',
    type: 'video' as const,
    category: 'stress' as const,
    duration: 900,
    thumbnail: 'https://images.unsplash.com/photo-1499209974431-9dddcece7f88?w=800',
    url: 'https://example.com/stress-management',
    author: 'Mark Williams',
    publishedAt: '2024-11-19T00:00:00Z',
    isBookmarked: true,
    viewCount: 3456,
    tags: ['stress', 'anxiety', 'coping'],
  },
  {
    id: '3',
    title: 'Better Sleep Habits',
    description: 'Science-backed tips to improve your sleep quality and wake up feeling refreshed.',
    type: 'article' as const,
    category: 'sleep' as const,
    readTime: 8,
    thumbnail: 'https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?w=800',
    url: 'https://example.com/sleep',
    author: 'Dr. Emily Chen',
    publishedAt: '2024-11-18T00:00:00Z',
    isBookmarked: false,
    viewCount: 2189,
    tags: ['sleep', 'health', 'habits'],
  },
  {
    id: '4',
    title: '10-Minute Guided Meditation',
    description: 'A calming guided meditation session perfect for beginners and experienced practitioners.',
    type: 'audio' as const,
    category: 'meditation' as const,
    duration: 600,
    thumbnail: 'https://images.unsplash.com/photo-1545389336-cf090694435e?w=800',
    url: 'https://example.com/meditation',
    author: 'Peaceful Mind Studio',
    publishedAt: '2024-11-17T00:00:00Z',
    isBookmarked: true,
    viewCount: 5678,
    tags: ['meditation', 'audio', 'relaxation'],
  },
  {
    id: '5',
    title: 'Overcoming Anxiety',
    description: 'Expert advice on understanding and managing anxiety with proven techniques.',
    type: 'article' as const,
    category: 'anxiety' as const,
    readTime: 12,
    thumbnail: 'https://images.unsplash.com/photo-1516302752625-fcc3c50ae61f?w=800',
    url: 'https://example.com/anxiety',
    author: 'Dr. Michael Brown',
    publishedAt: '2024-11-16T00:00:00Z',
    isBookmarked: false,
    viewCount: 4321,
    tags: ['anxiety', 'mental health', 'therapy'],
  },
  {
    id: '6',
    title: 'Building Healthy Relationships',
    description: 'Communication skills and strategies for maintaining strong, healthy relationships.',
    type: 'video' as const,
    category: 'relationships' as const,
    duration: 1200,
    thumbnail: 'https://images.unsplash.com/photo-1511632765486-a01980e01a18?w=800',
    url: 'https://example.com/relationships',
    author: 'Lisa Anderson',
    publishedAt: '2024-11-15T00:00:00Z',
    isBookmarked: false,
    viewCount: 2987,
    tags: ['relationships', 'communication', 'love'],
  },
  {
    id: '7',
    title: 'Boost Your Productivity',
    description: 'Time management techniques and productivity hacks to achieve your goals.',
    type: 'article' as const,
    category: 'productivity' as const,
    readTime: 7,
    thumbnail: 'https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?w=800',
    url: 'https://example.com/productivity',
    author: 'James Wilson',
    publishedAt: '2024-11-14T00:00:00Z',
    isBookmarked: true,
    viewCount: 3765,
    tags: ['productivity', 'focus', 'goals'],
  },
  {
    id: '8',
    title: 'Self-Care Essentials',
    description: 'Simple self-care practices to nurture your body, mind, and spirit.',
    type: 'article' as const,
    category: 'self-care' as const,
    readTime: 6,
    thumbnail: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800',
    url: 'https://example.com/self-care',
    author: 'Rachel Green',
    publishedAt: '2024-11-13T00:00:00Z',
    isBookmarked: false,
    viewCount: 2543,
    tags: ['self-care', 'wellness', 'health'],
  },
];
