// Mock Meditation Content
export const mockMeditationContent = [
  {
    id: 'm1',
    title: 'Morning Mindfulness',
    description: 'Start your day with clarity and calm. A gentle 10-minute practice to set positive intentions.',
    type: 'meditation' as const,
    category: 'mindfulness' as const,
    duration: 600,
    thumbnail: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800',
    url: 'https://example.com/morning-meditation',
    author: 'Peaceful Mind Studio',
    publishedAt: '2024-11-23T00:00:00Z',
    isBookmarked: false,
    viewCount: 8234,
    tags: ['morning', 'mindfulness', 'beginner'],
  },
  {
    id: 'm2',
    title: 'Stress Relief Session',
    description: 'Release tension and anxiety with this calming guided meditation. Perfect for busy days.',
    type: 'meditation' as const,
    category: 'stress' as const,
    duration: 900,
    thumbnail: 'https://images.unsplash.com/photo-1499209974431-9dddcece7f88?w=800',
    url: 'https://example.com/stress-relief',
    author: 'Calm Center',
    publishedAt: '2024-11-22T00:00:00Z',
    isBookmarked: true,
    viewCount: 12456,
    tags: ['stress', 'anxiety', 'relaxation'],
  },
  {
    id: 'm3',
    title: 'Deep Sleep Meditation',
    description: 'Drift into peaceful sleep with this soothing bedtime meditation practice.',
    type: 'meditation' as const,
    category: 'sleep' as const,
    duration: 1200,
    thumbnail: 'https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?w=800',
    url: 'https://example.com/sleep-meditation',
    author: 'Sleep Well Studio',
    publishedAt: '2024-11-21T00:00:00Z',
    isBookmarked: false,
    viewCount: 15678,
    tags: ['sleep', 'bedtime', 'relaxation'],
  },
  {
    id: 'm4',
    title: 'Body Scan Relaxation',
    description: 'Release physical tension with this progressive body scan meditation technique.',
    type: 'meditation' as const,
    category: 'mindfulness' as const,
    duration: 1500,
    thumbnail: 'https://images.unsplash.com/photo-1545389336-cf090694435e?w=800',
    url: 'https://example.com/body-scan',
    author: 'Mindful Living',
    publishedAt: '2024-11-20T00:00:00Z',
    isBookmarked: true,
    viewCount: 9876,
    tags: ['body scan', 'relaxation', 'mindfulness'],
  },
  {
    id: 'm5',
    title: 'Breathing Exercise',
    description: 'Simple yet powerful breathing techniques to calm your mind and reduce anxiety.',
    type: 'meditation' as const,
    category: 'anxiety' as const,
    duration: 480,
    thumbnail: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800',
    url: 'https://example.com/breathing',
    author: 'Breathe Easy',
    publishedAt: '2024-11-19T00:00:00Z',
    isBookmarked: false,
    viewCount: 7654,
    tags: ['breathing', 'anxiety', 'quick'],
  },
  {
    id: 'm6',
    title: 'Loving-Kindness Practice',
    description: 'Cultivate compassion and kindness towards yourself and others with this heart-opening meditation.',
    type: 'meditation' as const,
    category: 'mindfulness' as const,
    duration: 1080,
    thumbnail: 'https://images.unsplash.com/photo-1499209974431-9dddcece7f88?w=800',
    url: 'https://example.com/loving-kindness',
    author: 'Heart Space',
    publishedAt: '2024-11-18T00:00:00Z',
    isBookmarked: false,
    viewCount: 5432,
    tags: ['loving-kindness', 'compassion', 'heart'],
  },
];
